spring.application.name=simple-chatbot

spring.threads.virtual.enabled=true

## OpenAI
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-5-mini-2025-08-07
# spring.ai.openai.chat.options.model=gpt-4.1-mini-2025-04-14
spring.ai.openai.chat.options.temperature=1.0


## Ollama
# spring.ai.ollama.chat.options.model=llama3.2:1b
# spring.ai.ollama.chat.options.model=llama3.1
spring.ai.ollama.chat.options.model=llama3.2
spring.ai.ollama.embedding.options.model=mxbai-embed-large

## Anthropic Claude 3 (works in combination with Transformers (ONNX) embedding model)
spring.ai.anthropic.api-key=${ANTHROPIC_API_KEY}
spring.ai.anthropic.options.model=claude-sonnet-4-5-20250929

## Chroma
spring.ai.vectorstore.chroma.client.host=http://localhost
spring.ai.vectorstore.chroma.client.port=8000
spring.ai.vectorstore.chroma.initialize-schema=true
spring.ai.vectorstore.chroma.embedding-dimension=384

## Spring Docker Compose
spring.docker.compose.enabled=true
spring.docker.compose.file=docker-compose.yaml
spring.docker.compose.stop.command=down
